// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SailSight.Api.Data;

#nullable disable

namespace SailSight.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("UserId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Boat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoatClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("boat_class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SailNumber")
                        .HasColumnType("text")
                        .HasColumnName("sail_number");

                    b.HasKey("Id");

                    b.HasIndex("BoatClassId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("boats", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.BoatClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("boat_classes", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.BoatClassRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("boat_class_requests", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FinishLineSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("finish_line_source");

                    b.Property<Guid?>("FinishMark1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("finish_mark1_id");

                    b.Property<Guid?>("FinishMark2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("finish_mark2_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("StartLineSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_line_source");

                    b.Property<Guid?>("StartMark1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("start_mark1_id");

                    b.Property<Guid?>("StartMark2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("start_mark2_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("FinishMark1Id");

                    b.HasIndex("FinishMark2Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("StartMark1Id");

                    b.HasIndex("StartMark2Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.CourseLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("GateMarkId")
                        .HasColumnType("uuid")
                        .HasColumnName("gate_mark_id");

                    b.Property<string>("LegName")
                        .HasColumnType("text")
                        .HasColumnName("leg_name");

                    b.Property<string>("LegType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("leg_type");

                    b.Property<Guid>("MarkId")
                        .HasColumnType("uuid")
                        .HasColumnName("mark_id");

                    b.Property<double?>("OverrideRoundingRadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("override_rounding_radius_meters");

                    b.Property<string>("PassingSide")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passing_side");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("GateMarkId");

                    b.HasIndex("MarkId");

                    b.HasIndex("CourseId", "SortOrder")
                        .IsUnique();

                    b.ToTable("course_legs", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.DeclinationReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("DeclinationOffset")
                        .HasColumnType("real")
                        .HasColumnName("declination_offset");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("declinations", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.DepthReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("Depth")
                        .HasColumnType("real")
                        .HasColumnName("depth");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("depth_readings", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.LinePositionReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<short>("LineEnd")
                        .HasColumnType("smallint")
                        .HasColumnName("line_end");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("line_positions", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.LoadReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("Load")
                        .HasColumnType("real")
                        .HasColumnName("load");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_name");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("load_readings", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Mark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ActiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("active_from");

                    b.Property<DateOnly?>("ActiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("active_until");

                    b.Property<double>("DefaultRoundingRadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("default_rounding_radius_meters");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name", "ActiveFrom")
                        .IsUnique();

                    b.ToTable("marks", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.PositionReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("Altitude")
                        .HasColumnType("real")
                        .HasColumnName("altitude");

                    b.Property<float>("CourseOverGround")
                        .HasColumnType("real")
                        .HasColumnName("course_over_ground");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<float>("QuaternionW")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_w");

                    b.Property<float>("QuaternionX")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_x");

                    b.Property<float>("QuaternionY")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_y");

                    b.Property<float>("QuaternionZ")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_z");

                    b.Property<float>("SpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("speed_over_ground");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("analysis_status");

                    b.Property<int?>("CountdownDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("countdown_duration_seconds");

                    b.Property<DateTimeOffset?>("CountdownStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("countdown_started_at");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<float>("MaxSpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("max_speed_over_ground");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("race_number");

                    b.Property<double>("SailedDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("sailed_distance_meters");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SessionId", "RaceNumber")
                        .IsUnique();

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.RaceLegPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("AverageSpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("average_speed_over_ground");

                    b.Property<float>("AverageVelocityMadeGood")
                        .HasColumnType("real")
                        .HasColumnName("average_velocity_made_good");

                    b.Property<Guid>("CourseLegId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_leg_id");

                    b.Property<DateTimeOffset>("EnteredCurrentMarkAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_current_mark_at");

                    b.Property<DateTimeOffset>("ExitedPreviousMarkAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exited_previous_mark_at");

                    b.Property<int>("LegIndex")
                        .HasColumnType("integer")
                        .HasColumnName("leg_index");

                    b.Property<float>("MaxSpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("max_speed_over_ground");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<double>("SailedDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("sailed_distance_meters");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CourseLegId");

                    b.HasIndex("RaceId", "LegIndex")
                        .IsUnique();

                    b.ToTable("race_leg_performances", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.RaceTimerEvent", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<int>("TimerValue")
                        .HasColumnType("integer")
                        .HasColumnName("timer_value");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("race_timer_events", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BoatId")
                        .HasColumnType("uuid")
                        .HasColumnName("boat_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<short>("FormatVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("format_version");

                    b.Property<bool>("IsFixedToBodyFrame")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixed_to_body_frame");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("TelemetryRateHz")
                        .HasColumnType("smallint")
                        .HasColumnName("telemetry_rate_hz");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.HasIndex("CourseId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OwnerUserId", "ContentHash")
                        .IsUnique();

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.SessionShare", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("SessionId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("session_shares", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.ShiftAngleReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<bool>("IsPort")
                        .HasColumnType("boolean")
                        .HasColumnName("is_port");

                    b.Property<float>("SpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("speed_over_ground");

                    b.Property<float>("TrueHeading")
                        .HasColumnType("real")
                        .HasColumnName("true_heading");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("shift_angles", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.SpeedThroughWaterReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("ForwardSpeed")
                        .HasColumnType("real")
                        .HasColumnName("forward_speed");

                    b.Property<float>("HorizontalSpeed")
                        .HasColumnType("real")
                        .HasColumnName("horizontal_speed");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("speed_through_water", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.TeamInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeclinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declined_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("TeamId", "InvitedUserId");

                    b.ToTable("team_invites", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.TemperatureReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("temperature_readings", (string)null);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.WindReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("WindDirection")
                        .HasColumnType("real")
                        .HasColumnName("wind_direction");

                    b.Property<float>("WindSpeed")
                        .HasColumnType("real")
                        .HasColumnName("wind_speed");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("wind_readings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Boat", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.BoatClass", "BoatClass")
                        .WithMany()
                        .HasForeignKey("BoatClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoatClass");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.BoatClassRequest", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Course", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Mark", "FinishMark1")
                        .WithMany()
                        .HasForeignKey("FinishMark1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SailSight.Api.Models.Entities.Mark", "FinishMark2")
                        .WithMany()
                        .HasForeignKey("FinishMark2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.Mark", "StartMark1")
                        .WithMany()
                        .HasForeignKey("StartMark1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SailSight.Api.Models.Entities.Mark", "StartMark2")
                        .WithMany()
                        .HasForeignKey("StartMark2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FinishMark1");

                    b.Navigation("FinishMark2");

                    b.Navigation("StartMark1");

                    b.Navigation("StartMark2");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.CourseLeg", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Course", "Course")
                        .WithMany("Legs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.Mark", "GateMark")
                        .WithMany()
                        .HasForeignKey("GateMarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SailSight.Api.Models.Entities.Mark", "Mark")
                        .WithMany("CourseLegs")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("GateMark");

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.DeclinationReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.DepthReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.LinePositionReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.LoadReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Mark", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.PositionReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Race", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Course", "Course")
                        .WithMany("Races")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany("Races")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.RaceLegPerformance", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.CourseLeg", "CourseLeg")
                        .WithMany()
                        .HasForeignKey("CourseLegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.Race", "Race")
                        .WithMany("LegPerformances")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLeg");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.RaceTimerEvent", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Session", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Boat", "Boat")
                        .WithMany("Sessions")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SailSight.Api.Models.Entities.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.SessionShare", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany("Shares")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.ShiftAngleReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.SpeedThroughWaterReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Team", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.TeamInvite", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.AppUser", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.Team", "Team")
                        .WithMany("Invites")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.TeamMember", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SailSight.Api.Models.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.TemperatureReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.WindReading", b =>
                {
                    b.HasOne("SailSight.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Boat", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Course", b =>
                {
                    b.Navigation("Legs");

                    b.Navigation("Races");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Mark", b =>
                {
                    b.Navigation("CourseLegs");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Race", b =>
                {
                    b.Navigation("LegPerformances");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Session", b =>
                {
                    b.Navigation("Races");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("SailSight.Api.Models.Entities.Team", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
