name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Build API
        uses: ./.github/actions/build-api

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Build Web
        uses: ./.github/actions/build-web

  docker-api:
    name: Docker Build — API
    uses: ./.github/workflows/_docker-api.yml
    with:
      push: false

  docker-web:
    name: Docker Build — Web
    uses: ./.github/workflows/_docker-web.yml
    with:
      push: false
